development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: puntama_development
  host: localhost
  pool: 5
  username: vagrant
  password: test

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: puntama_test
  host: localhost
  pool: 5
  username: vagrant
  password: test
